# Generated by Django 5.0.7 on 2026-04-10 12:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("STUDENT", "Student"),
                            ("ACADEMIC_SUPERVISOR", "Academic Supervisor"),
                            ("WORKPLACE_SUPERVISOR", "Workplace Supervisor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("must_change_password", models.BooleanField(default=False)),
                ("phone_number", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student_id",
                    models.CharField(
                        help_text="Student ID number e.g. 260012345",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        help_text="Registration number e.g. 25/U/12345/EVE",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "college",
                    models.CharField(
                        help_text="E.g. CoCIS, CoCIT, CoHES, CoNAS, CoVET",
                        max_length=100,
                    ),
                ),
                (
                    "program",
                    models.CharField(
                        help_text="E.g. BSc Computer Science", max_length=100
                    ),
                ),
                (
                    "staff_id",
                    models.CharField(
                        blank=True,
                        help_text="University staff ID e.g. STF/2024/001",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "faculty",
                    models.CharField(
                        blank=True,
                        help_text="Faculty/College the supervisor belongs to",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="Official department within the university e.g. Computer Science, Electrical Engineering",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True,
                        help_text="Area of specialization e.g. Software Engineering, Data Science",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "max_students",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="Maximum number of interns this supervisor can handle at once",
                        null=True,
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True,
                        help_text="Supervisor's position at the workplace e.g. Senior Software Engineer",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "workplace_department",
                    models.CharField(
                        blank=True,
                        help_text="Department within the workplace e.g. IT, Finance, HR",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Years of professional experience",
                        null=True,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.CreateModel(
            name="AcademicDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the academic department e.g. Computer Science",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "faculty",
                    models.CharField(
                        help_text="Faculty/College the department belongs to e.g. CoCIS",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "head",
                    models.OneToOneField(
                        limit_choices_to={"role": "ACADEMIC_SUPERVISOR"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="department_head",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Department",
                "verbose_name_plural": "Academic Departments",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOG_CREATED", "Weekly Log Created"),
                            ("LOG_SUBMITTED", "Weekly Log Submitted"),
                            ("LOG_REVIEWED", "Weekly Log Reviewed"),
                            ("LOG_APPROVED", "Weekly Log Approved"),
                            ("LOG_REJECTED", "Weekly Log Rejected"),
                            ("REVIEW_COMPLETED", "Supervisor Review Completed"),
                            ("EVALUATION_CREATED", "Evaluation Created"),
                            ("EVALUATION_SUBMITTED", "Evaluation Submitted"),
                            ("PLACEMENT_APPROVED", "Placement Approved"),
                            ("PLACEMENT_REJECTED", "Placement Rejected"),
                            ("USER_CREATED", "User Created"),
                            ("USER_ROLE_CHANGED", "User Role Changed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        help_text="e.g., 'WeeklyLog', 'Evaluation'", max_length=50
                    ),
                ),
                ("object_id", models.IntegerField()),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TECHNICAL", "Technical Skills"),
                            ("SOFT_SKILLS", "Soft Skills"),
                            ("ATTENDANCE", "Attendance"),
                            ("CONDUCT", "Professional Conduct"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "weight",
                    models.FloatField(
                        help_text="Weight in percentage (e.g., 40, 30, 30)"
                    ),
                ),
                ("max_score", models.FloatField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_criteria",
                        to="core.academicdepartment",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Evaluation Criteria",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="InternshipPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("position_title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "academic_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placements",
                        to="core.academicdepartment",
                    ),
                ),
                (
                    "academic_supervisor",
                    models.ForeignKey(
                        limit_choices_to={"role": "ACADEMIC_SUPERVISOR"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supervised_placements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "ADMIN"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_placements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="internship_placements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workplace_supervisor",
                    models.ForeignKey(
                        limit_choices_to={"role": "WORKPLACE_SUPERVISOR"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workplace_supervised_placements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Internship Placements",
            },
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("technical_score", models.FloatField(blank=True, null=True)),
                ("soft_skills_score", models.FloatField(blank=True, null=True)),
                ("attendance_score", models.FloatField(blank=True, null=True)),
                ("conduct_score", models.FloatField(blank=True, null=True)),
                ("total_weighted_score", models.FloatField(blank=True, null=True)),
                ("final_grade", models.CharField(blank=True, max_length=2, null=True)),
                ("summary_comments", models.TextField(blank=True)),
                ("recommendation", models.TextField(blank=True)),
                ("is_submitted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(null=True)),
                (
                    "evaluator",
                    models.ForeignKey(
                        limit_choices_to={"role": "ACADEMIC_SUPERVISOR"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "placement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="core.internshipplacement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeeklyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.IntegerField()),
                ("week_start_date", models.DateField()),
                ("week_end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted for Review"),
                            ("REVIEWED", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("REVISE", "Revision Required"),
                        ],
                        default="DRAFT",
                        max_length=15,
                    ),
                ),
                ("activities_performed", models.TextField()),
                ("skills_acquired", models.TextField()),
                ("challenges_faced", models.TextField()),
                ("lessons_learned", models.TextField()),
                (
                    "hours_worked",
                    models.FloatField(
                        default=0, help_text="Total hours worked in the week"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(null=True)),
                ("reviewed_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                (
                    "placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_logs",
                        to="core.internshipplacement",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Weekly Logs",
                "ordering": ["-week_number"],
            },
        ),
        migrations.CreateModel(
            name="SupervisorReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "performance_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Poor"),
                            (2, "Below Average"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                (
                    "attendance_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Poor"),
                            (2, "Below Average"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                (
                    "attitude_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Poor"),
                            (2, "Below Average"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                ("comments", models.TextField()),
                ("recommendations", models.TextField(blank=True)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        limit_choices_to={"role": "WORKPLACE_SUPERVISOR"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supervisor_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "log",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor_review",
                        to="core.weeklylog",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Supervisor Reviews",
            },
        ),
        migrations.CreateModel(
            name="Workplace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the workplace e.g. XYZ Corporation",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Physical location of the workplace e.g. Kampala, Uganda",
                        max_length=255,
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        help_text="Industry sector e.g. Information Technology",
                        max_length=255,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        help_text="Contact email for internship coordination at the workplace",
                        max_length=254,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        help_text="Contact phone number for internship coordination at the workplace",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Intern Workpace",
                "verbose_name_plural": "Intern Workplaces",
                "indexes": [
                    models.Index(fields=["name"], name="core_workpl_name_ac87bd_idx"),
                    models.Index(
                        fields=["location"], name="core_workpl_locatio_152961_idx"
                    ),
                    models.Index(
                        fields=["industry"], name="core_workpl_industr_4642d3_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="internshipplacement",
            name="workplace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="internship_placements",
                to="core.workplace",
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["email"], name="core_custom_email_a5d01e_idx"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["role"], name="core_custom_role_77f64b_idx"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["phone_number"], name="core_custom_phone_n_7d1483_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["student_id"], name="core_custom_student_7545f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["registration_number"], name="core_custom_registr_c0e4b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["college"], name="core_custom_college_655aee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["program"], name="core_custom_program_c3da17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["staff_id"], name="core_custom_staff_i_67647d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["faculty"], name="core_custom_faculty_8f1605_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["specialization"], name="core_custom_special_71e26b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["max_students"], name="core_custom_max_stu_aac0c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["workplace_department"], name="core_custom_workpla_3cf054_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["years_of_experience"], name="core_custom_years_o_423cd2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["role", "faculty"], name="idx_role_faculty"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["role", "specialization"], name="idx_role_specialization"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["role", "max_students"], name="idx_role_max_students"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["role", "workplace_department"], name="idx_role_workplace_dept"
            ),
        ),
        migrations.AddIndex(
            model_name="academicdepartment",
            index=models.Index(fields=["name"], name="core_academ_name_93e4ef_idx"),
        ),
        migrations.AddIndex(
            model_name="academicdepartment",
            index=models.Index(
                fields=["faculty"], name="core_academ_faculty_845776_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicdepartment",
            index=models.Index(fields=["name", "faculty"], name="idx_name_faculty"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["actor", "timestamp"], name="core_auditl_actor_i_19c60f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["action"], name="core_auditl_action_d9fb24_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["timestamp"], name="core_auditl_timesta_80074f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evaluationcriteria",
            index=models.Index(
                fields=["department", "is_active"],
                name="core_evalua_departm_564fd3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="evaluation",
            index=models.Index(
                fields=["placement"], name="core_evalua_placeme_d775b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evaluation",
            index=models.Index(
                fields=["is_submitted"], name="core_evalua_is_subm_292909_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weeklylog",
            index=models.Index(
                fields=["placement", "week_number"],
                name="core_weekly_placeme_625a1f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="weeklylog",
            index=models.Index(fields=["status"], name="core_weekly_status_336a3e_idx"),
        ),
        migrations.AddIndex(
            model_name="weeklylog",
            index=models.Index(
                fields=["submitted_at"], name="core_weekly_submitt_445957_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklylog",
            constraint=models.UniqueConstraint(
                fields=("placement", "week_number"), name="unique_placement_week"
            ),
        ),
        migrations.AddIndex(
            model_name="supervisorreview",
            index=models.Index(
                fields=["approval_status"], name="core_superv_approva_931116_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="internshipplacement",
            index=models.Index(
                fields=["student", "status"], name="core_intern_student_00a112_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="internshipplacement",
            index=models.Index(
                fields=["start_date", "end_date"], name="core_intern_start_d_f1f290_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="internshipplacement",
            index=models.Index(fields=["status"], name="core_intern_status_2d5af3_idx"),
        ),
        migrations.AddConstraint(
            model_name="internshipplacement",
            constraint=models.UniqueConstraint(
                fields=("student", "workplace", "start_date", "end_date"),
                name="unique_student_workplace_period",
            ),
        ),
    ]
