# Generated by Django 5.0.7 on 2026-06-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="college",
            field=models.CharField(
                blank=True,
                help_text="E.g. CoCIS, CoCIT, CoHES, CoNAS, CoVET",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="program",
            field=models.CharField(
                blank=True,
                help_text="E.g. BSc Computer Science",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="registration_number",
            field=models.CharField(
                blank=True,
                help_text="Registration number e.g. 25/U/12345/EVE",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="student_id",
            field=models.CharField(
                blank=True,
                help_text="Student ID number e.g. 260012345",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
